version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: best_choice
      MYSQL_USER: hh2003
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./demo
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/best_choice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db: